server {
    listen 80;
    server_name da.utwoa.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name da.utwoa.ru;

    ssl_certificate /etc/letsencrypt/live/da.utwoa.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/da.utwoa.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /opt/Database-administration/portal;
    index index.html;

    location = /v1 {
        return 301 /v1/;
    }

    location = /v2 {
        return 301 /v2/;
    }

    location = /v3 {
        return 301 /v3/;
    }

    location = /v4 {
        return 301 /v4/;
    }

    location = /v5 {
        return 301 /v5/;
    }

    location = /v6 {
        return 301 /v6/;
    }

    location = /v7 {
        return 301 /v7/;
    }

    location = /v8 {
        return 301 /v8/;
    }

    location ^~ /v1/static/ {
        alias /opt/Database-administration/v1.0/static/;
        access_log off;
        expires 7d;
        try_files $uri =404;
    }

    location /v1/ {
        proxy_pass http://127.0.0.1:8001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /v1;
        proxy_redirect off;
    }

    location /v2/ {
        alias /opt/Database-administration/portal/versions/v2/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v3/ {
        alias /opt/Database-administration/portal/versions/v3/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v4/ {
        alias /opt/Database-administration/portal/versions/v4/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v5/ {
        alias /opt/Database-administration/portal/versions/v5/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v6/ {
        alias /opt/Database-administration/portal/versions/v6/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v7/ {
        alias /opt/Database-administration/portal/versions/v7/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /v8/ {
        alias /opt/Database-administration/portal/versions/v8/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
