services:
  mongodb:
    image: ${MONGO_IMAGE}
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - mongo_network

  mongo-express:
    image: ${MONGO_EXPRESS_IMAGE}
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mongo_network
volumes:
  mongo_data:
networks:
  mongo_network:
